const products = [
  {
    name: 'Ethiopian Yirgacheffe',
    image: 'https://images.unsplash.com/photo-1587734195503-904fca479805?auto=format&fit=crop&q=80',
    description: 'Bright, floral notes with a hint of citrus. Medium roast.',
    category: 'Single Origin',
    price: 2500,
    countInStock: 25,
    rating: 4.8,
    numReviews: 12,
  },
  {
    name: 'Colombian Supremo',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80',
    description: 'Rich, full-bodied flavor with caramel undertones. Dark roast.',
    category: 'Single Origin',
    price: 2200,
    countInStock: 40,
    rating: 4.6,
    numReviews: 8,
  },
  {
    name: 'Espresso Blend',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80',
    description: 'A perfect balance of Robusta and Arabica for the perfect crema.',
    category: 'Blends',
    price: 1800,
    countInStock: 50,
    rating: 4.9,
    numReviews: 20,
  },
  {
    name: 'Decaf House Blend',
    image: 'https://images.unsplash.com/photo-1524350876685-274059332603?auto=format&fit=crop&q=80',
    description: 'All the flavor without the jitters. Swiss Water Process.',
    category: 'Decaf',
    price: 1950,
    countInStock: 15,
    rating: 4.5,
    numReviews: 5,
  },
   {
    name: 'Sumatra Mandheling',
    image: 'https://images.unsplash.com/photo-1559525839-b184a4d698c7?auto=format&fit=crop&q=80',
    description: 'Earth, herbal notes with a heavy body and low acidity.',
    category: 'Single Origin',
    price: 2800,
    countInStock: 30,
    rating: 4.7,
    numReviews: 15,
  },
  {
    name: 'Breakfast Blend',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80',
    description: 'Light and crisp, the perfect way to start your day.',
    category: 'Blends',
    price: 1650,
    countInStock: 60,
    rating: 4.4,
    numReviews: 10,
  }
];

module.exports = products;
